version = 0.1

[[task]]
name = "run"
dep = "server.js"
run = "node server.js"

[[task]]
name = "build"
deps = ['public/##.html.js', 'public/importmap.json', 'public/credt.js']
target = 'public/##.html'
run = 'node $DEP > $TARGET'
