packages:
  - "packages/core"
  - "packages/crdt"
  - "packages/server"
  - "packages/tsconfig"
  - "packages/ts-dot-js/cli"
  - "packages/ts-dot-js/typescript-plugin"
  - "packages/ts-dot-js/vscode-extension"
  - "examples/*"
