version = 0.1

[[task]]
name = "clean"
run = "rimraf build/ dist/"

[[task]]
name = "copy-js"
dep = "clean"
run = "mkdir -p build; cp -r src/ build/ts-dot-js/"

[[task]]
name = "make-ts"
deps = ["copy-js", "build/ts-dot-js/##.js"]
run = "ts-dot-js $DEP"

[[task]]
name = "build-unminified"
deps = ["clean"]
run = "esbuild --bundle --format=esm --external:linkedom --external:./ssr/index.js --external:node:* --outfile=dist/index.js src/index.js"

[[task]]
name = "build-minified"
deps = ["clean"]
run = "esbuild --bundle --format=esm --external:linkedom --external:./ssr/index.js --external:node:* --outfile=dist/index.min.js --minify src/index.js"

[[task]]
name = "build-minified-compressed"
deps = ["build-minified"]
run = "brotli dist/index.min.js"

[[task]]
name = "build-types"
deps = ["make-ts"]
run = "tsc -p tsconfig.build.json"

[[task]]
name = "build"
deps = ["build-types", "build-unminified", "build-minified-compressed"]
